### DISCUSSION TITLE
How to correctly provide more information about an endpoint?

### DISCUSSION THREAD

**Discussion by talyh** [SamWSoftware/serverless-auto-swagger#129] [Q&A]
I've been trying to wrap my head around how to go about

> The default swagger file from vanilla Serverless framework will have the correct paths and methods but no details about the requests or responses.

(as indicated in the README)

The way I understand it, this won't be something done in the the `serverless.yaml`. file, but rather on the swagger json files.
Assuming that interpretation is correct, now the question is "how to do this in a way that isn't overwrritten by subsequent auto generations of the docs?"

I initially thought it was through the `swaggerFiles` attribute, where I'd provide additional definitions for a route and the auto generation would merge that with the info derived from the `serverless.yaml`
However, that didn't work (see configuration below).
The generated `swagger.js` file only considers what's in the `serverless`. What's the correct way to extend the definitions in the serverless to ensure proper maintainability of the docs?

For instance
```yaml
# serverless.yaml

custom:
  autoswagger:
    swaggerFiles: [./docs/getPMCComplianceConfig.json]

functions:
  getPMCComplianceConfig:
    handler: handler.getPMCComplianceConfigHandler
    name: compliance-config-service-getPMCComplianceConfig-${sls:stage}
    events:
      - httpApi:
          path: /compliance/pmc/{id}/config
          method: get
```

```json
-- docs/getPMCComplianceConfig.json
{
  "paths": {
    "/compliance/pmc/{id}/config": {
      "get": {
        "description": "Something",
        "responses": {
          "200": {
            "description": "200 blah"
          },
          "500": {
            "description": "500 bleh"
          }
        }
      }
    }
  }
}
```

```js
// auto generated swagger
"paths": {
    "/compliance/pmc/{id}/config": {
      "get": {
        "summary": "getPMCComplianceConfig",
        "description": "",
        "operationId": "getPMCComplianceConfig.get./compliance/pmc/{id}/config",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
```
