### ISSUE TITLE
ModuleNotFoundError Received when running sls offline for a Python project.

### ISSUE THREAD

**Issue by ezzy1337** [SamWSoftware/serverless-auto-swagger#10]
I didn't see it explicitly stated anywhere but does this plugin work for a serverless application that is not typescript?

Given the error I'm seeing it looks like Python is trying to import the `html.js` file from the pregenerated `swagger` folder which is an invalid import. 

```
Traceback (most recent call last):
  File "/Users/derek/platform-api/services/checkpoint-service/node_modules/serverless-offline/dist/lambda/handler-runner/python-runner/invoke.py", line 76, in <module>

    module = import_module(args.handler_path.replace(os.sep, '.'))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'swagger.html'
```

Here is the configuration I've provided for the plugin.
```
  autoswagger:
    generateSwaggerOnDeploy?: true
    typefiles?: [ './schemas/checkpoint.d.ts' ]
```

I added the `typefiles?` portion and the checkpoint.d.ts file just to see if it resolved the import but to no avail.

Other Pertinent Details:
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.0.1
     Framework Version:         2.71.0 (local)
     Plugin Version:            5.5.3
     SDK Version:               4.3.0
     Components Version:        3.18.1
```

**Comment by SamWSoftware** [comment]
I've never tested it with a python project. The endpoint that it makes by default is a Javascript one. Not sure how that will work with a python serverless project.

If there was a way to check if the project was js or python then the plugin could swap out the html.js for an equivalent python lambda

**Comment by ezzy1337** [comment]
I think we could use the `runtime` field under the `provider` section in the serverless.yml file to determine if it's a javascript or python project. 

Over the weekend I played around with a basic python serverless app. The basic python app would get the same error `ModuleNotFoundError: No module named 'swagger.html'`. but if I changed the `runtime` from `python3.8` to `nodejs12.x` the swagger endpoints would work.

If you can point me in the right direction I'd be happy to work on this.

For reference here is the serverless.yml file I was working with.

```
org: ddrummond
app: serverless-docs-python
service: serverless-docs-python

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8  # <-- I think we could use the 
  lambdaHashingVersion: 20201221

functions:
  health:
    handler: handler.health
    events:
      - http:
          method: get
          path: /health
          cors: true

plugins:
  - serverless-auto-swagger
  - serverless-offline
```
