### ISSUE TITLE
unrecognized custom.autoswagger description and version

### ISSUE THREAD

**Issue by matiasict** [SamWSoftware/serverless-auto-swagger#143]
i'm configuring auto swagger (v3.1.0) in serverless.yml, it is not recognizing “version” and “description”. what could be happening?

serverless.yml:

```
autoswagger:
    swaggerPath: 'site/swagger'
    apiType: httpApi
    title: Backoffice API
    description: API del Backoffice
    version: '2.0.0'
    excludeStages: ['stage', 'prod']
    typefiles: [
      './packages/swagger/types/types.d.ts'
      ]
```

Error:

<img width="826" alt="Image" src="https://github.com/user-attachments/assets/b411f0fa-11d6-4b80-b0aa-931e35265e46" />
