### ISSUE TITLE
Bug: OperationId is repeated on multiple http events with same method, in same handler

### ISSUE THREAD

**Issue by jochembeetz** [SamWSoftware/serverless-auto-swagger#42]
In my serverless I have configured:

```
functions:
  fooHandler:
    handler: src/handler/foo.handler
    events:
      - http:
         path: /foo
         method: get
      - http:
         path: /foo/{id}
         method: get
```

This will result in a bug in the swagger UI where it opens both items if I click to open one of those items.

Validator.swagger error message:
`
{
"messages": [
"attribute paths.'/installations/{id}'(get).operationId is repeated"
]
}
`
