### ISSUE TITLE
Improvement: Specify stages for excluding swagger endpoints

### ISSUE THREAD

**Issue by jochembeetz** [SamWSoftware/serverless-auto-swagger#46]
As of right now, swagger endpoints are always added. I want my swagger to only be generated and/or deployed when the stage is development or staging.

Suggestion:

```
custom:
  autoswagger:
      stages:
         - staging
         - development
```

**Comment by jochembeetz** [comment]
I wanted to create a pull request but it seems this isn't possible yet.

I will leave change suggestion here:

serverlessPlugin.d.ts
```
export interface AutoSwaggerCustomConfig {
  autoswagger?: {
    apiType?: ApiType
    apiKeyHeaders?: string[]
    swaggerFiles?: string[]
    generateSwaggerOnDeploy?: boolean
    typefiles?: string[]
    useStage?: boolean
    swaggerPath?: string
    basePath?: string
    schemes?: SwaggerScheme[]
    stages?: string[] <--------- NEW
  }
}
```

ServerlessAutoSwagger.ts
```
  predeploy = async () => {
    const stage = this.serverless.service.provider.stage; <---------- NEW
    const specifiedStages = this.serverless.service.custom?.autoswagger?.stages; <---------- NEW
    if(specifiedStages && specifiedStages.indexOf(stage) === -1) { <---------- NEW
      console.log(`Not deploying for stage: ${stage} due to custom.autoswagger.stages configuration.`); <---------- NEW
      return; <---------- NEW
    } <---------- NEW

    const generateSwaggerOnDeploy =
      this.serverless.service.custom?.autoswagger?.generateSwaggerOnDeploy;
    if (generateSwaggerOnDeploy === undefined || generateSwaggerOnDeploy) {
      await this.generateSwagger();
    }

    this.addEndpointsAndLambda();
  };
```

**Comment by bfaulk96** [comment]
I would think you could already do that with something like

Serverless 2.0.0:
```yaml
custom:
  generateSwagger:
    staging: true
    development: true
    prod: false
  autoswagger:
    generateSwaggerOnDeploy: ${{self:custom.generateSwagger.${{self:provider.stage}}}} 
```

Serverless 3.0.0:
```yaml
params:
  default:
    generateSwagger: false
  staging:
    generateSwagger: true
  development:
    generateSwagger: true
custom:
  autoswagger:
    generateSwaggerOnDeploy: ${param:generateSwagger}
```
