### ISSUE TITLE
Not recognized options in js

### ISSUE THREAD

**Issue by PraveenApplogiq** [SamWSoftware/serverless-auto-swagger#49]
```

  autoswagger:
    apiType?: "httpApi"
    generateSwaggerOnDeploy: true
    typefiles?: []
    swaggerFiles: ["api/swaggerJson/login.json", "api/swaggerJson/users.json"]
    swaggerPath?: "http://localhost:3000/apiDocs"
    apiKeyHeaders?: "string[]"
    useStage?: true
    basePath?: "/dev/"
    schemes: ["http", "https"]
    excludeStages?: ["dev"]
```

serverless generate swagger not taking the options which i was giving in the serverless.yml file.

**Comment by bfaulk96** [comment]
Can you provide more information? There's not really anything to work off of here. I can with confidence tell you that what is pasted above is not valid yaml, however.

**Comment by bfaulk96** [comment]
The `?:` was used to indicate these were all optional. Based on what I'm seeing above, your custom yaml should look more like
```yaml
  autoswagger:
    apiType: "httpApi"
    generateSwaggerOnDeploy: true
    swaggerFiles: ["api/swaggerJson/login.json", "api/swaggerJson/users.json"]
    swaggerPath: "apiDocs"
    useStage: true
    basePath: "/dev"
    schemes: ["http", "https"]
    excludeStages: ["dev"]
```

But I foresee you having some issues with this configuration as well, since you're both setting base path to dev as well as trying to exclude dev..
