### ISSUE TITLE
Path parameters

### ISSUE THREAD

**Issue by mzawitowski** [SamWSoftware/serverless-auto-swagger#60]
Plugin version 2.4.0.

I was able to present path params only by duplicating the path:
```
handler: src/handler.hello
    events:
      - httpApi:
          path: hello/{helloId}
          method: post
          parameters:
            path: hello/{helloId}
```

Btw. no idea how to add any description to them.

**Comment by ronie-san** [comment]
The `pathToParam` function inside `ServerlessAutoSwagger` doesn't have the `description` param and neither that function has the implementation.

But theoretically, you could this:
```yml
handler: src/handler.hello
    events:
      - httpApi:
          path: hello/{helloId}
          method: post
          parameters:
            path:
              helloId:
                type: string
                description: Hello ID
```
