### ISSUE TITLE
serverless-webpack & serverless-offline support?

### ISSUE THREAD

**Issue by bcrigler** [SamWSoftware/serverless-auto-swagger#66]
So, I see you support `serverless-offline`, although I can't seem to get my documentation to load at the route /swagger.  It gives me a 404, and the only thing I can think of is it's because I'm using `serverless-webpack`.

My Config:
```
custom:
  autoswagger:
    generateSwaggerOnDeploy: true
    typefiles: ['./src/models/response/body.response.d.ts']
    apiKeyHeaders: ['Authorization']
    swaggerPath: "documentation"
    useStage: false
```

My Plugins: (I also tried with `serverless-auto-swagger` above `serverless-webpack`)

```
plugins:
  - serverless-webpack
  - serverless-auto-swagger
  - serverless-offline
  - serverless-deployment-bucket
```

NPM Module Versions:  (from package.json)

```
"serverless": "^2.72.3",
"serverless-auto-swagger": "^2.4.1",
"serverless-deployment-bucket": "^1.5.2",
"serverless-offline": "8.5.0",
"serverless-webpack": "5.6.1",
```
