### ISSUE TITLE
Skip Stage not working as expected.

### ISSUE THREAD

**Issue by bcrigler** [SamWSoftware/serverless-auto-swagger#72]
The skip stage param is an array of environments to avoid deploying to.  If I pass it an array of ["stage", "prod"] to only have my documentation on my "dev" environment, it then attempts to deploy the function with the "dev" stage name into the other environments.

So, ```{myproject-name}-dev-swagger-ui``` (dev being my stage) is being deployed into both the ```{myproject-name}-stage``` as well as ```{myproject-name}-prod``` APIGateways.  So, all it's really doing is using the available stage name ("dev") and still actually attempting to deploy to the stages I told it to bypass.  

Am I missing something or misunderstanding what this param is used for?

**Comment by bfaulk96** [comment]
Please provide more complete information including the specific "skip stage param" code block as well as what version of Serverless and this plugin you are using.

The param is called `excludeStages`, so if you are using something like `skipStage` it would not work.

I can confirm that `excludeStages` works as expected using the latest version of this plugin and Serverless 3, as I am using it myself in several projects and it is not creating any lambdas.

**Comment by bcrigler** [comment]
Can you please explain what "excludeStages" does or is supposed to do?

My understanding was that adding it in would mean that the Lambdas would not be deployed to those stages.

I am using ```"serverless": "^2.72.3"``` and ```"serverless-auto-swagger": "^2.4.1"```

```
custom:
  autoswagger:
    generateSwaggerOnDeploy: true
    typefiles: ['types/api-types.d.ts']
    apiKeyHeaders: ['Authorization']
    swaggerFiles: ['swagger.json']
    swaggerPath: "documentation"
    useStage: false
    apiType: "http"
    excludeStages: ["stage", "prod"]
```
